<?php
/**
 * This file has been automaticaly generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Bolbo\Component\Model\Database\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Product
 *
 * Structure class for relation public.product.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Product extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.product')
            ->setPrimaryKey(['product_id'])
            ->addField('product_id', 'int4')
            ->addField('author_id', 'int4')
            ->addField('created_at', 'timestamp')
            ->addField('updated_at', 'timestamp')
            ->addField('deleted_at', 'timestamp')
            ->addField('status', 'int4')
            ->addField('reference', 'varchar')
            ->addField('title', 'varchar')
            ->addField('description', 'text')
            ->addField('caracteristic', 'public.hstore')
            ->addField('price', 'float8')
            ;
    }
}
